// TSLib - A free TeamSpeak 3 and 5 client library
// Copyright (C) 2017  TSLib contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the Open Software License v. 3.0
//
// You should have received a copy of the Open Software License along with this
// program. If not, see <https://opensource.org/licenses/OSL-3.0>.
// <auto-generated />

#nullable enable
using System;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TSLib;

public static class TsTypes
{
	public static Type[] All => new Type[] { typeof(Uid),typeof(ClientDbId),typeof(ClientId),typeof(ChannelId),typeof(ServerGroupId),typeof(ChannelGroupId), };
}

[StructLayout(LayoutKind.Sequential, Pack=0)]
[DebuggerDisplay("{Value, nq}")]
[JsonConverter(typeof(Uid.Converter))]
public readonly partial record struct Uid
{
	public static readonly Uid Null = new Uid(string.Empty);
	public static Uid To(String v) => new Uid(v);

	public String Value { get; }
	public Uid(String value) { if (value == null) throw new ArgumentNullException(nameof(value)); Value = value; }
	public static explicit operator Uid(String v) => new Uid(v);
	public override string ToString() => Value ?? "";
	public static Uid? TryFrom(object value) {
		if (value is string s) return new Uid(s);
		return null;
	}

	private sealed class Converter : JsonConverter<Uid>
	{
		public override Uid Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
			=> new Uid(reader.GetString() ?? throw new FormatException());
		public override void Write(Utf8JsonWriter writer, Uid value, JsonSerializerOptions options)
			=> writer.WriteStringValue(value.Value);
	}
}

[StructLayout(LayoutKind.Sequential, Pack=0)]
[DebuggerDisplay("{Value, nq}")]
[JsonConverter(typeof(ClientDbId.Converter))]
public readonly partial record struct ClientDbId : IFormattable
{
	public static readonly ClientDbId Null = new ClientDbId(default);
	public static ClientDbId To(UInt64 v) => new ClientDbId(v);

	public UInt64 Value { get; }
	public ClientDbId(UInt64 value) { Value = value; }
	public static explicit operator ClientDbId(UInt64 v) => new ClientDbId(v);
	public override string ToString() => Value.ToString();
	public string ToString(string? format, IFormatProvider? formatProvider) => Value.ToString(format, formatProvider);
	public static ClientDbId? TryFrom(object value) {
		if (value is UInt64 bvalue) return new ClientDbId(bvalue);
		if (value is string s && UInt64.TryParse(s, out var num)) return new ClientDbId(num);
		if (value is IConvertible c) return new ClientDbId(c.ToUInt64(CultureInfo.InvariantCulture));

		return null;
	}

	private sealed class Converter : JsonConverter<ClientDbId>
	{
		public override ClientDbId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
			=> new ClientDbId(reader.TokenType == JsonTokenType.String
				? UInt64.Parse(reader.GetString()!, CultureInfo.InvariantCulture)
				: reader.GetUInt64());
		public override void Write(Utf8JsonWriter writer, ClientDbId value, JsonSerializerOptions options)
			=> writer.WriteNumberValue(value.Value);
	}
}

[StructLayout(LayoutKind.Sequential, Pack=0)]
[DebuggerDisplay("{Value, nq}")]
[JsonConverter(typeof(ClientId.Converter))]
public readonly partial record struct ClientId : IFormattable
{
	public static readonly ClientId Null = new ClientId(default);
	public static ClientId To(UInt16 v) => new ClientId(v);

	public UInt16 Value { get; }
	public ClientId(UInt16 value) { Value = value; }
	public static explicit operator ClientId(UInt16 v) => new ClientId(v);
	public override string ToString() => Value.ToString();
	public string ToString(string? format, IFormatProvider? formatProvider) => Value.ToString(format, formatProvider);
	public static ClientId? TryFrom(object value) {
		if (value is UInt16 bvalue) return new ClientId(bvalue);
		if (value is string s && UInt16.TryParse(s, out var num)) return new ClientId(num);
		if (value is IConvertible c) return new ClientId(c.ToUInt16(CultureInfo.InvariantCulture));

		return null;
	}

	private sealed class Converter : JsonConverter<ClientId>
	{
		public override ClientId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
			=> new ClientId(reader.TokenType == JsonTokenType.String
				? UInt16.Parse(reader.GetString()!, CultureInfo.InvariantCulture)
				: reader.GetUInt16());
		public override void Write(Utf8JsonWriter writer, ClientId value, JsonSerializerOptions options)
			=> writer.WriteNumberValue(value.Value);
	}
}

[StructLayout(LayoutKind.Sequential, Pack=0)]
[DebuggerDisplay("{Value, nq}")]
[JsonConverter(typeof(ChannelId.Converter))]
public readonly partial record struct ChannelId : IFormattable
{
	public static readonly ChannelId Null = new ChannelId(default);
	public static ChannelId To(UInt64 v) => new ChannelId(v);

	public UInt64 Value { get; }
	public ChannelId(UInt64 value) { Value = value; }
	public static explicit operator ChannelId(UInt64 v) => new ChannelId(v);
	public override string ToString() => Value.ToString();
	public string ToString(string? format, IFormatProvider? formatProvider) => Value.ToString(format, formatProvider);
	public static ChannelId? TryFrom(object value) {
		if (value is UInt64 bvalue) return new ChannelId(bvalue);
		if (value is string s && UInt64.TryParse(s, out var num)) return new ChannelId(num);
		if (value is IConvertible c) return new ChannelId(c.ToUInt64(CultureInfo.InvariantCulture));

		return null;
	}

	private sealed class Converter : JsonConverter<ChannelId>
	{
		public override ChannelId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
			=> new ChannelId(reader.TokenType == JsonTokenType.String
				? UInt64.Parse(reader.GetString()!, CultureInfo.InvariantCulture)
				: reader.GetUInt64());
		public override void Write(Utf8JsonWriter writer, ChannelId value, JsonSerializerOptions options)
			=> writer.WriteNumberValue(value.Value);
	}
}

[StructLayout(LayoutKind.Sequential, Pack=0)]
[DebuggerDisplay("{Value, nq}")]
[JsonConverter(typeof(ServerGroupId.Converter))]
public readonly partial record struct ServerGroupId : IFormattable
{
	public static readonly ServerGroupId Null = new ServerGroupId(default);
	public static ServerGroupId To(UInt64 v) => new ServerGroupId(v);

	public UInt64 Value { get; }
	public ServerGroupId(UInt64 value) { Value = value; }
	public static explicit operator ServerGroupId(UInt64 v) => new ServerGroupId(v);
	public override string ToString() => Value.ToString();
	public string ToString(string? format, IFormatProvider? formatProvider) => Value.ToString(format, formatProvider);
	public static ServerGroupId? TryFrom(object value) {
		if (value is UInt64 bvalue) return new ServerGroupId(bvalue);
		if (value is string s && UInt64.TryParse(s, out var num)) return new ServerGroupId(num);
		if (value is IConvertible c) return new ServerGroupId(c.ToUInt64(CultureInfo.InvariantCulture));

		return null;
	}

	private sealed class Converter : JsonConverter<ServerGroupId>
	{
		public override ServerGroupId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
			=> new ServerGroupId(reader.TokenType == JsonTokenType.String
				? UInt64.Parse(reader.GetString()!, CultureInfo.InvariantCulture)
				: reader.GetUInt64());
		public override void Write(Utf8JsonWriter writer, ServerGroupId value, JsonSerializerOptions options)
			=> writer.WriteNumberValue(value.Value);
	}
}

[StructLayout(LayoutKind.Sequential, Pack=0)]
[DebuggerDisplay("{Value, nq}")]
[JsonConverter(typeof(ChannelGroupId.Converter))]
public readonly partial record struct ChannelGroupId : IFormattable
{
	public static readonly ChannelGroupId Null = new ChannelGroupId(default);
	public static ChannelGroupId To(UInt64 v) => new ChannelGroupId(v);

	public UInt64 Value { get; }
	public ChannelGroupId(UInt64 value) { Value = value; }
	public static explicit operator ChannelGroupId(UInt64 v) => new ChannelGroupId(v);
	public override string ToString() => Value.ToString();
	public string ToString(string? format, IFormatProvider? formatProvider) => Value.ToString(format, formatProvider);
	public static ChannelGroupId? TryFrom(object value) {
		if (value is UInt64 bvalue) return new ChannelGroupId(bvalue);
		if (value is string s && UInt64.TryParse(s, out var num)) return new ChannelGroupId(num);
		if (value is IConvertible c) return new ChannelGroupId(c.ToUInt64(CultureInfo.InvariantCulture));

		return null;
	}

	private sealed class Converter : JsonConverter<ChannelGroupId>
	{
		public override ChannelGroupId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
			=> new ChannelGroupId(reader.TokenType == JsonTokenType.String
				? UInt64.Parse(reader.GetString()!, CultureInfo.InvariantCulture)
				: reader.GetUInt64());
		public override void Write(Utf8JsonWriter writer, ChannelGroupId value, JsonSerializerOptions options)
			=> writer.WriteNumberValue(value.Value);
	}
}
