// TSLib - A free TeamSpeak 3 and 5 client library
// Copyright (C) 2017  TSLib contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the Open Software License v. 3.0
//
// You should have received a copy of the Open Software License along with this
// program. If not, see <https://opensource.org/licenses/OSL-3.0>.
// <auto-generated />




using System.Collections.Generic;

#pragma warning disable CS8019 // Ignore unused imports
using i8  = System.SByte;
using u8  = System.Byte;
using i16 = System.Int16;
using u16 = System.UInt16;
using i32 = System.Int32;
using u32 = System.UInt32;
using i64 = System.Int64;
using u64 = System.UInt64;
using f32 = System.Single;
using f64 = System.Double;
using str = System.String;

using DateTime = System.DateTime;
using Duration = System.TimeSpan;
using DurationSeconds = System.TimeSpan;
using DurationMilliseconds = System.TimeSpan;
using DurationMillisecondsFloat = System.TimeSpan;
using SocketAddr = System.String;
using IpAddr = System.String;
using Ts3ErrorCode = TSLib.TsErrorCode;
using Ts3Permission = TSLib.TsPermission;

using IconHash = System.Int32;
using IconId = System.Int32;
using ConnectionId = System.UInt32;
using EccKeyPubP256 = TSLib.Uid;
#pragma warning restore CS8019

#nullable enable
namespace TSLib.Full.Book;

public sealed partial class ServerGroup
{
	#pragma warning disable CS8618
	public ServerGroup()
	#pragma warning restore CS8618
	{
	}

	public GroupType GroupType { get; set; }
	public IconId Icon { get; set; }
	public ServerGroupId Id { get; set; }
	public bool IsPermanent { get; set; }
	public str Name { get; set; }
	public GroupNamingMode NamingMode { get; set; }
	public i32 NeededMemberAddPower { get; set; }
	public i32? NeededMemberRemovePower { get; set; }
	public i32 NeededModifyPower { get; set; }
	public i32 SortId { get; set; }
}
public sealed partial class ChannelGroup
{
	#pragma warning disable CS8618
	public ChannelGroup()
	#pragma warning restore CS8618
	{
	}

	public GroupType GroupType { get; set; }
	public IconId Icon { get; set; }
	public ChannelGroupId Id { get; set; }
	public bool IsPermanent { get; set; }
	public str Name { get; set; }
	public GroupNamingMode NamingMode { get; set; }
	public i32 NeededMemberAddPower { get; set; }
	public i32? NeededMemberRemovePower { get; set; }
	public i32 NeededModifyPower { get; set; }
	public i32 SortId { get; set; }
}
public sealed partial class OptionalChannelData
{
	#pragma warning disable CS8618
	public OptionalChannelData()
	#pragma warning restore CS8618
	{
	}

	public str Description { get; set; }
}
public sealed partial class Channel
{
	#pragma warning disable CS8618
	public Channel()
	#pragma warning restore CS8618
	{
	}

	public ChannelType ChannelType { get; set; }
	public Codec Codec { get; set; }
	public i32? CodecLatencyFactor { get; set; }
	public u8? CodecQuality { get; set; }
	public Duration? DeleteDelay { get; set; }
	public bool ForcedSilence { get; set; }
	public str? Guid { get; set; }
	public bool? HasPassword { get; set; }
	public IconId? Icon { get; set; }
	public ChannelId Id { get; set; }
	public bool? IsDefault { get; set; }
	public bool? IsPrivate { get; set; }
	public bool? IsUnencrypted { get; set; }
	public MaxClients? MaxClients { get; set; }
	public MaxClients? MaxFamilyClients { get; set; }
	public str Name { get; set; }
	public i32? NeededTalkPower { get; set; }
	public OptionalChannelData? OptionalData { get; set; }
	public ChannelId Order { get; set; }
	public ChannelId Parent { get; set; }
	public ChannelPermissionHint? PermissionHints { get; set; }
	public str? PhoneticName { get; set; }
	public u32? StorageQuota { get; set; }
	public bool Subscribed { get; set; }
	public str? Topic { get; set; }
}
public sealed partial class OptionalClientData
{
	#pragma warning disable CS8618
	public OptionalClientData()
	#pragma warning restore CS8618
	{
	}

	public u64 BytesDownloadedMonth { get; set; }
	public u64 BytesDownloadedTotal { get; set; }
	public u64 BytesUploadedMonth { get; set; }
	public u64 BytesUploadedTotal { get; set; }
	public u32 ConnectionsTotal { get; set; }
	public DateTime Created { get; set; }
	public DateTime LastConnected { get; set; }
	public str? LoginName { get; set; }
	public str Platform { get; set; }
	public str Version { get; set; }
	public str? VersionSign { get; set; }
}
public sealed partial class ConnectionClientData
{
	#pragma warning disable CS8618
	public ConnectionClientData()
	#pragma warning restore CS8618
	{
	}

	public u64? BandwidthReceivedLastMinuteControl { get; set; }
	public u64? BandwidthReceivedLastMinuteKeepalive { get; set; }
	public u64? BandwidthReceivedLastMinuteSpeech { get; set; }
	public u64? BandwidthReceivedLastSecondControl { get; set; }
	public u64? BandwidthReceivedLastSecondKeepalive { get; set; }
	public u64? BandwidthReceivedLastSecondSpeech { get; set; }
	public u64? BandwidthSentLastMinuteControl { get; set; }
	public u64? BandwidthSentLastMinuteKeepalive { get; set; }
	public u64? BandwidthSentLastMinuteSpeech { get; set; }
	public u64? BandwidthSentLastSecondControl { get; set; }
	public u64? BandwidthSentLastSecondKeepalive { get; set; }
	public u64? BandwidthSentLastSecondSpeech { get; set; }
	public u64? BytesReceivedControl { get; set; }
	public u64? BytesReceivedKeepalive { get; set; }
	public u64? BytesReceivedSpeech { get; set; }
	public u64? BytesSentControl { get; set; }
	public u64? BytesSentKeepalive { get; set; }
	public u64? BytesSentSpeech { get; set; }
	public SocketAddr? ClientAddress { get; set; }
	public f32 ClientToServerPacketlossControl { get; set; }
	public f32 ClientToServerPacketlossKeepalive { get; set; }
	public f32 ClientToServerPacketlossSpeech { get; set; }
	public f32 ClientToServerPacketlossTotal { get; set; }
	public Duration? ConnectedTime { get; set; }
	public u64? FiletransferBandwidthReceived { get; set; }
	public u64? FiletransferBandwidthSent { get; set; }
	public Duration IdleTime { get; set; }
	public u64? PacketsReceivedControl { get; set; }
	public u64? PacketsReceivedKeepalive { get; set; }
	public u64? PacketsReceivedSpeech { get; set; }
	public u64? PacketsSentControl { get; set; }
	public u64? PacketsSentKeepalive { get; set; }
	public u64? PacketsSentSpeech { get; set; }
	public Duration? Ping { get; set; }
	public Duration? PingDeviation { get; set; }
	public f32? ServerToClientPacketlossControl { get; set; }
	public f32? ServerToClientPacketlossKeepalive { get; set; }
	public f32? ServerToClientPacketlossSpeech { get; set; }
	public f32? ServerToClientPacketlossTotal { get; set; }
}
public sealed partial class Client
{
	#pragma warning disable CS8618
	public Client()
	#pragma warning restore CS8618
	{
		ServerGroups = new HashSet<ServerGroupId>();
	}

	public str AvatarHash { get; set; }
	public str? AwayMessage { get; set; }
	public str Badges { get; set; }
	public ChannelId Channel { get; set; }
	public ChannelGroupId ChannelGroup { get; set; }
	public ClientType ClientType { get; set; }
	public ConnectionClientData? ConnectionData { get; set; }
	public str CountryCode { get; set; }
	public ClientDbId DatabaseId { get; set; }
	public str Description { get; set; }
	public IconId Icon { get; set; }
	public ClientId Id { get; set; }
	public ChannelId InheritedChannelGroupFromChannel { get; set; }
	public bool InputHardwareEnabled { get; set; }
	public bool InputMuted { get; set; }
	public bool IsChannelCommander { get; set; }
	public bool IsPrioritySpeaker { get; set; }
	public bool IsRecording { get; set; }
	public str Metadata { get; set; }
	public str Name { get; set; }
	public i32 NeededServerqueryViewPower { get; set; }
	public OptionalClientData? OptionalData { get; set; }
	public bool OutputHardwareEnabled { get; set; }
	public bool OutputMuted { get; set; }
	public bool OutputOnlyMuted { get; set; }
	public ClientPermissionHint? PermissionHints { get; set; }
	public str PhoneticName { get; set; }
	public HashSet<ServerGroupId> ServerGroups { get; set; }
	public i32 TalkPower { get; set; }
	public bool TalkPowerGranted { get; set; }
	public TalkPowerRequest? TalkPowerRequest { get; set; }
	public Uid? Uid { get; set; }
	public u32 UnreadMessages { get; set; }
	public str? UserTag { get; set; }
}
public sealed partial class OptionalServerData
{
	#pragma warning disable CS8618
	public OptionalServerData()
	#pragma warning restore CS8618
	{
	}

	public u32 AntifloodPointsTickReduce { get; set; }
	public u32 AntifloodPointsToCommandBlock { get; set; }
	public u32 AntifloodPointsToIpBlock { get; set; }
	public u32 AntifloodPointsToPluginBlock { get; set; }
	public bool Autostart { get; set; }
	public u64 BytesDownloadedMonth { get; set; }
	public u64 BytesDownloadedTotal { get; set; }
	public u64 BytesUploadedMonth { get; set; }
	public u64 BytesUploadedTotal { get; set; }
	public u64 ChannelCount { get; set; }
	public u16 ClientCount { get; set; }
	public u32 ComplainAutobanCount { get; set; }
	public Duration ComplainAutobanTime { get; set; }
	public Duration ComplainRemoveTime { get; set; }
	public u64 ConnectionCountTotal { get; set; }
	public ChannelGroupId DefaultChannelAdminGroup { get; set; }
	public u64 DownloadQuota { get; set; }
	public bool HasPassword { get; set; }
	public bool LogChannel { get; set; }
	public bool LogClient { get; set; }
	public bool LogFiletransfer { get; set; }
	public bool LogPermissions { get; set; }
	public bool LogQuery { get; set; }
	public bool LogServer { get; set; }
	public str MachineId { get; set; }
	public u64 MaxDownloadBandwidthTotal { get; set; }
	public u64 MaxUploadBandwidthTotal { get; set; }
	public DateTime MinAndroidVersion { get; set; }
	public u32 MinClientsInChannelBeforeForcedSilence { get; set; }
	public DateTime MinClientVersion { get; set; }
	public DateTime MinIosVersion { get; set; }
	public u8 NeededIdentitySecurityLevel { get; set; }
	public u16 Port { get; set; }
	public u32 QueryCount { get; set; }
	public u64 QueryCountTotal { get; set; }
	public u16 ReservedSlots { get; set; }
	public f32 TotalPacketloss { get; set; }
	public f32 TotalPacketlossControl { get; set; }
	public f32 TotalPacketlossKeepalive { get; set; }
	public f32 TotalPacketlossSpeech { get; set; }
	public Duration TotalPing { get; set; }
	public u64 UploadQuota { get; set; }
	public Duration Uptime { get; set; }
	public bool WeblistEnabled { get; set; }
}
public sealed partial class ConnectionServerData
{
	#pragma warning disable CS8618
	public ConnectionServerData()
	#pragma warning restore CS8618
	{
	}

	public u64 BandwidthReceivedLastMinuteTotal { get; set; }
	public u64 BandwidthReceivedLastSecondTotal { get; set; }
	public u64 BandwidthSentLastMinuteTotal { get; set; }
	public u64 BandwidthSentLastSecondTotal { get; set; }
	public u64 BytesReceivedTotal { get; set; }
	public u64 BytesSentTotal { get; set; }
	public Duration ConnectedTimeTotal { get; set; }
	public u64 FiletransferBandwidthReceived { get; set; }
	public u64 FiletransferBandwidthSent { get; set; }
	public u64 FiletransferBytesReceivedTotal { get; set; }
	public u64 FiletransferBytesSentTotal { get; set; }
	public f32 PacketlossTotal { get; set; }
	public u64 PacketsReceivedTotal { get; set; }
	public u64 PacketsSentTotal { get; set; }
	public Duration Ping { get; set; }
}
public sealed partial class Server
{
	#pragma warning disable CS8618
	public Server()
	#pragma warning restore CS8618
	{
		Ips = new List<IpAddr>();
	}

	public str? AdministrativeDomain { get; set; }
	public bool AskForPrivilegekey { get; set; }
	public CodecEncryptionMode CodecEncryptionMode { get; set; }
	public ConnectionServerData? ConnectionData { get; set; }
	public DateTime Created { get; set; }
	public ChannelGroupId DefaultChannelGroup { get; set; }
	public ServerGroupId DefaultServerGroup { get; set; }
	public Duration HostbannerGfxInterval { get; set; }
	public str HostbannerGfxUrl { get; set; }
	public HostBannerMode HostbannerMode { get; set; }
	public str HostbannerUrl { get; set; }
	public str HostbuttonGfxUrl { get; set; }
	public str HostbuttonTooltip { get; set; }
	public str HostbuttonUrl { get; set; }
	public str Hostmessage { get; set; }
	public HostMessageMode HostmessageMode { get; set; }
	public IconId Icon { get; set; }
	public u64 Id { get; set; }
	public List<IpAddr> Ips { get; set; }
	public LicenseType License { get; set; }
	public u16 MaxClients { get; set; }
	public str Name { get; set; }
	public str? Nickname { get; set; }
	public OptionalServerData? OptionalData { get; set; }
	public str PhoneticName { get; set; }
	public str Platform { get; set; }
	public f32 PrioritySpeakerDimmModificator { get; set; }
	public u16 ProtocolVersion { get; set; }
	public EccKeyPubP256 PublicKey { get; set; }
	public Duration TempChannelDefaultDeleteDelay { get; set; }
	public str Version { get; set; }
	public str WelcomeMessage { get; set; }
}
public sealed partial class Connection
{
	#pragma warning disable CS8618
	public Connection()
	#pragma warning restore CS8618
	{
		Clients = new Dictionary<ClientId,Client>();
		Channels = new Dictionary<ChannelId,Channel>();
		ServerGroups = new Dictionary<ServerGroupId,ServerGroup>();
		ChannelGroups = new Dictionary<ChannelGroupId,ChannelGroup>();
	}

	public Dictionary<ChannelGroupId,ChannelGroup> ChannelGroups { get; set; }
	public Dictionary<ChannelId,Channel> Channels { get; set; }
	public Dictionary<ClientId,Client> Clients { get; set; }
	public ClientId OwnClient { get; set; }
	public Server Server { get; set; }
	public Dictionary<ServerGroupId,ServerGroup> ServerGroups { get; set; }
}
